# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_distromap.ui'
#
# Created: Thu Feb 21 11:28:49 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DistroMap(object):
    def setupUi(self, DistroMap):
        DistroMap.setObjectName(_fromUtf8("DistroMap"))
        DistroMap.resize(387, 538)
        self.gridLayout_3 = QtGui.QGridLayout(DistroMap)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(DistroMap)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(DistroMap)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboSecondary = QtGui.QComboBox(DistroMap)
        self.comboSecondary.setObjectName(_fromUtf8("comboSecondary"))
        self.gridLayout.addWidget(self.comboSecondary, 1, 1, 1, 1)
        self.comboSurface = QtGui.QComboBox(DistroMap)
        self.comboSurface.setObjectName(_fromUtf8("comboSurface"))
        self.gridLayout.addWidget(self.comboSurface, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(DistroMap)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(DistroMap)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBase = QtGui.QComboBox(DistroMap)
        self.comboBase.setObjectName(_fromUtf8("comboBase"))
        self.gridLayout.addWidget(self.comboBase, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(DistroMap)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.comboLocalities = QtGui.QComboBox(DistroMap)
        self.comboLocalities.setObjectName(_fromUtf8("comboLocalities"))
        self.verticalLayout.addWidget(self.comboLocalities)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(DistroMap)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.comboTaxonField = QtGui.QComboBox(DistroMap)
        self.comboTaxonField.setObjectName(_fromUtf8("comboTaxonField"))
        self.verticalLayout_2.addWidget(self.comboTaxonField)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(DistroMap)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.comboGrid = QtGui.QComboBox(DistroMap)
        self.comboGrid.setObjectName(_fromUtf8("comboGrid"))
        self.verticalLayout_3.addWidget(self.comboGrid)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 3, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_8 = QtGui.QLabel(DistroMap)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.leMaxY = QtGui.QLineEdit(DistroMap)
        self.leMaxY.setObjectName(_fromUtf8("leMaxY"))
        self.gridLayout_2.addWidget(self.leMaxY, 0, 1, 1, 1)
        self.leMinX = QtGui.QLineEdit(DistroMap)
        self.leMinX.setObjectName(_fromUtf8("leMinX"))
        self.gridLayout_2.addWidget(self.leMinX, 1, 0, 1, 1)
        self.leMaxX = QtGui.QLineEdit(DistroMap)
        self.leMaxX.setObjectName(_fromUtf8("leMaxX"))
        self.gridLayout_2.addWidget(self.leMaxX, 1, 2, 1, 1)
        self.leMinY = QtGui.QLineEdit(DistroMap)
        self.leMinY.setObjectName(_fromUtf8("leMinY"))
        self.gridLayout_2.addWidget(self.leMinY, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 4, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_9 = QtGui.QLabel(DistroMap)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leOutDir = QtGui.QLineEdit(DistroMap)
        self.leOutDir.setPlaceholderText(_fromUtf8(""))
        self.leOutDir.setObjectName(_fromUtf8("leOutDir"))
        self.horizontalLayout.addWidget(self.leOutDir)
        self.btnBrowse = QtGui.QPushButton(DistroMap)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 5, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(DistroMap)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 6, 0, 1, 1)

        self.retranslateUi(DistroMap)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DistroMap.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DistroMap.reject)
        QtCore.QMetaObject.connectSlotsByName(DistroMap)

    def retranslateUi(self, DistroMap):
        DistroMap.setWindowTitle(QtGui.QApplication.translate("DistroMap", "Distribution Map Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DistroMap", "Background layers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DistroMap", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DistroMap", "Secondary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DistroMap", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DistroMap", "Point localities layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DistroMap", "Taxon identifier field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DistroMap", "Grid layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DistroMap", "Output extent:", None, QtGui.QApplication.UnicodeUTF8))
        self.leMaxY.setText(QtGui.QApplication.translate("DistroMap", "-21.00", None, QtGui.QApplication.UnicodeUTF8))
        self.leMinX.setText(QtGui.QApplication.translate("DistroMap", "14.75", None, QtGui.QApplication.UnicodeUTF8))
        self.leMaxX.setText(QtGui.QApplication.translate("DistroMap", "34.00", None, QtGui.QApplication.UnicodeUTF8))
        self.leMinY.setText(QtGui.QApplication.translate("DistroMap", "-36.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DistroMap", "Output directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("DistroMap", "Browse...", None, QtGui.QApplication.UnicodeUTF8))

